### ISSUE TITLE
What have we here???

### ISSUE THREAD

**Issue by WiggleGiggle** [dukeofdoom007/DankAngels#1]
Uhhhhh you left something that should be in env... just gonna leave to find it

**Comment by dukeofdoom007** [comment]
I am not a fool to leave a valid token in env

**Comment by dukeofdoom007** [comment]
Also it's not a raid bot lol, i was testing out some new pycord stuff

**Comment by WiggleGiggle** [comment]
so you arent quiting discord...

**Comment by dukeofdoom007** [comment]
Already did, just coming on once in 3-4 days or once a week to check on updates/new features and rest
